-- SUPERSEDED — do not run this file.
--
-- This was an earlier, divergent draft of the Phase 06 schema (steeping_circles,
-- circle_enrollments, membrane_pings), written separately from supabase_phase06_schema.sql
-- and never fully applied — confirmed 2026-09-06 by reading the live database directly:
-- the tables that exist today match supabase_phase06_schema.sql's shapes (composite PKs on
-- circle_enrollments, DATE fields on steeping_circles, etc.), not this file's (separate `id`
-- PKs, TIMESTAMPTZ fields, a different action_type comment listing 'VESSEL_OPENED' etc.).
--
-- One thing in this file WAS applied, apparently by hand, outside any tracked migration:
-- `ALTER PUBLICATION supabase_realtime ADD TABLE membrane_pings;` (line 65 of the original).
-- Confirmed still live via `SELECT * FROM pg_publication_tables WHERE pubname = 'supabase_realtime'`.
-- That fact — and the metadata column added by the Sage-as-Point-Guard work — now live in
-- supabase_phase06_schema.sql instead, so there is one authoritative file for this table's
-- shape, not two disagreeing ones.
--
-- This file is kept only so the filename doesn't silently vanish from history for anyone
-- who finds it referenced elsewhere (ROADMAP_PHASE_06.md, etc.). If you're looking for the
-- real, live schema for these tables: supabase_phase06_schema.sql.
